travis:
  secure:
    BINSTAR_TOKEN: JR5XsIeK+Ep6jg2d3CBaiv45WTOuqEmXkwc9eHjRsiIrHlhr2FvIvjK9pf5RO1V4R8pDPzZYWP6c4DI4UmOlrTLLNTuxTcpIK6dyImPikhpUKxYPhBPPmFY8pXyW59rcWSozmsw9hDTaKaWW1xkjiNivcd1iCzIPDhQVEU+Jn61e44HQcVDXyQbRn8ceF/KIz/Lk1fH54BXvjRRGMSZuERR3i0AqJTZhekhQ0NFrUuP3Wcl78mci5v206yQ8hyxeTJa77TBD3i6wG8BYvLwOkJLJk0ne++NWFYI+GvEEip33UL/uw5XlOuwZRimzn8QueKqVoOZkp3DpvqhOjX+B+2ZVRDJP+UC8rVvgMYLCvdQsiZsl0CpTM8nPf8D6nzENRvkfd0ApppSYBiQwlXJG8EDxA4UHdcSelbB6c8mQqNhPN5Gag0Pt/7FZ2100HYjp53sZH7AVMej4gbok/IX7xTe/2X8STalu10e/mBhiXmyj5gPCp0IaaCu3D1VUm2vAanG/n0KHqPcIo1yxqcik+/Z2XiyKd8oz1Go4pwY/3wfRtdHu+U4dWof34j3vsxrAuQ1JORbZzxa2CW0UB0xmhBjSaDWL55mwSV9qx7G2nc75i77v8KHQNel8JDKNQiQ33coNKJgy6fmJCwCaTxk56DBntvPacwdCGraaO7eURg8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
